import numpy as np
import matplotlib.pyplot as plt
x1=np.linspace(0.0,0.5)
x2=np.linspace(0.0,0.2)
y1=np.cos(2*np.pi*x1)*np.exp(-x1)
y2=np.cos(2*np.pi*x2)
plt.subplot(2,1,1)
plt.plot(x1,y1,'o-')
plt.title("subplot")
plt.xlabel('time')
plt.ylabel('freq')
plt.subplot(2,1,2)
plt.plot(x2,y2,'--')
plt.title("subplot2")
plt.xlabel("year")
plt.ylabel('month')
plt.show()
